FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir pandas matplotlib numpy seaborn scipy

RUN groupadd -g 1410 appgroup && \
    useradd -u 1410 -g appgroup -m -s /bin/bash appuser

USER appuser

# docker build -t mads-sandbox-base -f infras/docker/Dockerfile.sandbox .