x-healthcheck-defaults: &healthcheck_base
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 10s

x-postgres-env: &postgres-env
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

x-minio-env: &minio-env
  S3_ENDPOINT: ${S3_ENDPOINT}
  MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
  MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
  UPLOAD_BUCKET: ${UPLOAD_BUCKET}
  OLIST_DATA: ${OLIST_DATA}

x-qdrant-env: &qdrant-env
  QDRANT_KEY: ${QDRANT_KEY}
  QDRANT_ENDPOINT: ${QDRANT_ENDPOINT}


services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: mads-postgres
    environment:
      <<: *postgres-env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/01-create-readonly-user.sh
    healthcheck:
      <<: *healthcheck_base
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]

  qdrant:
    image: qdrant/qdrant:v1.17
    ports:
      - "6333:6333"
    environment:
      <<: *qdrant-env
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      <<: *healthcheck_base
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"]

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      <<: *minio-env
    volumes:
      - minio_data:/data
    healthcheck:
      <<: *healthcheck_base
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]

  ingestion:
    build:
      context: ../../
      dockerfile: infras/docker/Dockerfile.ingestion
    command: python data/ingestion.py
    env_file:
      - ../../.env.dev
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ../../core:/app/core
      - ../../data:/app/data
      - ../../api/models:/app/api/models

  grant_permissions:
    image: postgres:${POSTGRES_VERSION}
    depends_on:
      postgres:
        condition: service_healthy
      ingestion:
        condition: service_completed_successfully
    env_file:
      - ../../.env.dev
    volumes:
      - ../../scripts:/scripts
    entrypoint: >
      bash -c "
      export PGPASSWORD=$POSTGRES_PASSWORD &&
      psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -f /scripts/grant_readonly.sql
      "

  api:
    build:
      context: ../../
      dockerfile: infras/docker/Dockerfile.api
    command: >
      uvicorn api.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    env_file:
      - ../../.env.dev
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      ingestion:
        condition: service_completed_successfully 
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      mcp_server:
        condition: service_healthy

    ports:
      - "8000:8000"
    volumes:
      - ../../api:/app/api         
      - ../../core:/app/core       
      - ../../shared_tmp:/tmp/uploads
    image: mads-backend
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      <<: *healthcheck_base 
      test: ["CMD", "redis-cli", "ping"]
  
  celery_worker:
    image: mads-backend
    command: celery -A core.worker worker --loglevel=debug
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    env_file:
      - ../../.env.dev
    volumes:
      - ../../api:/app/api          
      - ../../core:/app/core        
      - ../../shared_tmp:/tmp/uploads

  mcp_server:
    build:
      context: ../../
      dockerfile: infras/docker/Dockerfile.mcp
    env_file:
      - ../../.env.dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ../../shared_tmp:/tmp/uploads
      - ../../mcp_server:/app/mcp_server
    environment:
      - MCP_PORT=${MCP_PORT}
      - MCP_HOST=${MCP_HOST}
    healthcheck:
      <<: *healthcheck_base
      test: ["CMD-SHELL", "python -c \"import socket; socket.create_connection(('127.0.0.1', 8001))\" || exit 1"]

  sandbox_api:
    build:
      context: ../../
      dockerfile: infras/docker/Dockerfile.sandbox_api
    environment:
      - HOST_SHARED_TMP_DIR=${HOST_SHARED_TMP_DIR}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../shared_tmp:/tmp/uploads
      - ../../sandbox_api:/app/sandbox_api
    ports:
      - "8002:8002"

volumes:
  pgdata:
  minio_data:
  redis_data:
  qdrant_data: